### ISSUE TITLE
Can we have a rewrite?

### ISSUE THREAD

**Issue by MathieDev** [EricAndrechek/VCController#7]
This crashes my discord when opening a connection to the local api.

**Comment by Piripe** [comment]
I'm working on it, I'll fork this repo when I finish

**Comment by EricAndrechek** [comment]
@Piripe Thanks for taking this on. Let me know when you're done with your fork of this and I'll mark this repo as archived and put a message in the README to redirect people to yours.

**Comment by Piripe** [comment]
I just finished the rewrite:
https://github.com/Piripe/BDPlugins

I'll ask a BD moderator to add DCController (The new name of the plugin) to the official plugins list.

If you want, you can add this line to the VCController meta (to update everyone who downloads VCController):
```
 * @updateUrl https://github.com/Piripe/BDPlugins/raw/main/Plugins/DCController/DCController.plugin.js
```
<br/>

Changelog (Because Discord do not show it when installing the plugin):

New Stuff:
- Web documentation is now available (http://127.0.0.1:6969/docs)
- New requests: `/start_video`, `/stop_stream`, `/stop_video`, `/version`

Improvements:
- Plugin rewritten/updated and renamed to DCController.
- A modal is now open to restart Discord when the plugin is stopped.

Bug Fixes:
- Web server is no longer open when the plugin is loaded.

On-going:
- More requests being added. (Send message, join VC and other things like that)
- Settings modal being added.

**Comment by MathieDev** [comment]
Thank you so much, I will definitely be using this.

**Comment by EricAndrechek** [comment]
Thanks, @Piripe, I have added a note to the readme and changed the update URL. Now archiving the repo so as to not create confusion.
